import {
  TrendingUp,
  Activity,
  Zap,
  Factory,
  ShoppingBag,
  Tv,
  Landmark,
  GraduationCap,
  Truck,
  ShieldAlert,
  Building,
  Wheat,
  Search,
  Menu,
  X,
  ExternalLink,
  ChevronRight,
  Clock,
  BarChart3,
  CheckCircle,
  AlertTriangle,
  Info,
} from 'lucide-react'
import type { Sector } from './types'

export const SectorIcons: Record<Sector, typeof TrendingUp> = {
  Finance: TrendingUp,
  Healthcare: Activity,
  Energy: Zap,
  Manufacturing: Factory,
  Retail: ShoppingBag,
  Media: Tv,
  Government: Landmark,
  Education: GraduationCap,
  Transportation: Truck,
  Cybersecurity: ShieldAlert,
  'Real Estate': Building,
  Agriculture: Wheat,
}

export const Icons = {
  ...SectorIcons,
  Search,
  Menu,
  X,
  ExternalLink,
  ChevronRight,
  Clock,
  Chart: BarChart3,
  Check: CheckCircle,
  Alert: AlertTriangle,
  Info,
  Activity,
  Zap,
  TrendingUp,
}
