import { Activity, Zap, TrendingUp, AlertTriangle, CheckCircle, Info } from 'lucide-react'
import type { AIOpinion } from '@/lib/types'

interface NuaicoLensProps {
  aiOpinion: AIOpinion
}

export default function NuaicoLens({ aiOpinion }: NuaicoLensProps) {
  const confidenceColor =
    aiOpinion.confidenceLevel === 'High'
      ? 'text-emerald-600 bg-emerald-50 border-emerald-200'
      : 'text-amber-600 bg-amber-50 border-amber-200'

  return (
    <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
      <div className="bg-brand-dark px-6 py-4 flex items-center justify-between">
        <h2 className="text-white font-heading font-bold text-xl flex items-center gap-2">
          <Activity className="text-brand-accent" /> Nuaico Lens
        </h2>
        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-400">Analysis Confidence:</span>
          <span className={`text-xs font-bold px-2 py-0.5 rounded border ${confidenceColor}`}>
            {aiOpinion.confidenceLevel}
          </span>
        </div>
      </div>

      <div className="p-6 md:p-8 space-y-8">
        {/* Change & Impact */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <h4 className="font-bold text-slate-900 mb-2 text-sm uppercase flex items-center gap-2">
              <Zap size={16} className="text-amber-500" /> What Changes
            </h4>
            <p className="text-slate-700 text-sm leading-relaxed">
              {aiOpinion.change}
            </p>
          </div>
          <div>
            <h4 className="font-bold text-slate-900 mb-2 text-sm uppercase flex items-center gap-2">
              <TrendingUp size={16} className="text-emerald-500" /> Who Benefits / Disrupted
            </h4>
            <p className="text-slate-700 text-sm leading-relaxed">
              {aiOpinion.beneficiaries}
            </p>
          </div>
        </div>

        {/* Risks */}
        <div>
          <h4 className="font-bold text-slate-900 mb-3 text-sm uppercase flex items-center gap-2">
            <AlertTriangle size={16} className="text-red-500" /> Critical Risks & Unknowns
          </h4>
          <ul className="space-y-2">
            {aiOpinion.risks.map((risk, i) => (
              <li key={i} className="flex gap-3 text-sm text-slate-700">
                <span className="text-red-400">&#8226;</span> {risk}
              </li>
            ))}
          </ul>
        </div>

        {/* Takeaways */}
        <div className="bg-slate-50 rounded-lg p-6 border border-slate-100">
          <h4 className="font-bold text-slate-900 mb-3 text-sm uppercase flex items-center gap-2">
            <CheckCircle size={16} className="text-brand-accent" /> Key Takeaways
          </h4>
          <ul className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {aiOpinion.takeaways.map((point, i) => (
              <li key={i} className="text-sm text-slate-700 font-medium">
                {i + 1}. {point}
              </li>
            ))}
          </ul>
        </div>

        <div className="text-xs text-gray-400 border-t border-gray-100 pt-4 flex items-center gap-2">
          <Info size={12} />
          Nuaico&apos;s opinion is generated by AI models trained to be analytical and unbiased.
        </div>
      </div>
    </div>
  )
}
